sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        # https://github.com/getsentry/sentry-symfony#step-3-configure-the-sdk
        # https://docs.sentry.io/platforms/php/#php-specific-options
        excluded_exceptions:
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
