# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "bootstrap-5.3.2" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-5.3.2.tgz";
        sha512 = "D32nmNWiQHo94BKHLmOrdjlL05q1c8oxbtBphQFb9Z5to6eGRDCm0QgeaZ4zFBHzfg2++rqa2JkqCcxDy0sH0g==";
      };
    };
  };
  args = {
    name = "_at_darkwood-com_slash_darkwood-com";
    packageName = "@darkwood-com/darkwood-com";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."bootstrap-5.3.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Darkwood website";
      homepage = "https://github.com/darkwood-com/darkwood-com#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
